local layout = Layout.new{
	cellRelW = 0.2, cellRelH = 0.5,
	anAdd = Layout.newAnimation(),
	anRemove = Layout.newAnimation(),
	Layout.new{
		texture = skyworldTexture,
		texM = Layout.FIT_ALL,
		TextField.new(font, "FIT_ALL", "|"),
		col = 0, row = 0,
	},
	Layout.new{
		texture = skyworldTexture,
		texM = Layout.STRETCH,
		TextField.new(font, "STRETCH", "|"),
		col = 1, row = 0,
	},
	Layout.new{
		texture = skyworldTexture,
		texM = Layout.FIT_WIDTH,
		TextField.new(font, "FIT_WIDTH", "|"),
		col = 2, row = 0,
	},
	Layout.new{
		texture = skyworldTexture,
		texM = Layout.FIT_HEIGHT,
		TextField.new(font, "FIT_HEIGHT", "|"),
		col = 3, row = 0,
	},
	Layout.new{
		texture = skyworldTexture,
		texM = Layout.CROP,
		TextField.new(font, "CROP", "|"),
		col = 4, row = 0,
	},
	Layout.new{
		cellRelH = 1/4,
		Layout.new{row = 0,
			TextField.new(font, "texM = Layout.CROP", "|"),
		},
		Layout.new{row = 1,
			TextField.new(font, "texX = 0.75", "|"),
		},
		Layout.new{row = 2,
			TextField.new(font, "texY = 0.25", "|"),
		},
		Layout.new{row = 3,
			TextField.new(font, "texS = 1.5", "|"),
		},
		texture = skyworldTexture,
		texM = Layout.CROP, texX = 0.75, texY = 0.25, texS = 1.5,
		col = 0, row = 1, colW = 5,
	},	
}

stage:addChild(layout)